### PR TITLE
Ensure Gitnuro follows macOS theme and add missing app icon

### PR DESCRIPTION
**Pull request by ProjectInfinity**
By default Gitnuro ignores system theme and uses a white window decoration even if system is set to dark mode.
This fixes that.

On an unrelated note, the tests are failing on my mac but I'm not familiar with junit (or kotlin actually but there's a first for anything). Is there something I need to set up for the tests to not fail?

### CODE REVIEW

**Comment by JetpackDuba** [comment]
Thanks for the first PR and the tests report 😊

Tests fixed, should work properly now.

About the PR itself: Looks correct but I'd like to test it. I'll leave the PR on hold until I can check it, I'll come back to it in about ~3 weeks.

**Comment by ProjectInfinity** [comment]
I have tested that with/without the line it does indeed change the color of the window decoration on macOS.

I also made a icon.icns file (at the resolution of 512x512) from the SVG since the original size was problematic to turn into an Apple icns file, this has been set as the app icon.

Screenshot 2022-05-31 at 17 50 22

**Comment by ProjectInfinity** [comment]
The icon needs a little work on mac. It is currently a bit too big, very obvious if you place two next to each other in the dock. macOS has a guideline regarding icon (roundedness etc) I will try to redo the ICNS to make it fit better in on apple devices. Update coming.

**Comment by JetpackDuba** [comment]
It's possible that it uses a transparent padding so the icon itself does not touch the edges of the image (just a theory, haven't checked). Let me know if you need help with that.

**Comment by ProjectInfinity** [comment]
I took the resolution of 512x512 and scaled the layer down 19.5% which is the default macOS padding. Looks much better.

image

**Pull request merged**
